### PR TITLE
misc: update golangci-lint and use cached action

### PR DESCRIPTION
**Pull request by thor**
Disable depguard as it's unconfigured and ignore the noop logger for unused parameters.

### CODE REVIEW

**Comment by thor** [comment]
Do you want to merge the other PR as-is, @hanssto, and then we can rebase and merge this one? It looks like it'd be nice to have the full history for these smaller changes.

**Comment by thor** [comment]
> I'm torn between "I shouldn't spend more time on this" and "I should rework the other PR so that it's more sane in the event of us ever merging this back upstream". I will let tomorrow-me decide as I have to pick up the spawn.

My suggestion is, @hanssto:

1. Merge the _base_ branch of this PR as a squash as all the changes are the same in nature.
2. Merge this via rebase and merge to the main branch.

Au voila.

**Comment by thor** [comment]
> @thor I've cleaned up #34 now, squashing the commits manually and giving them a more unified explanation. Lemme know if it's readable.

@hanssto Looks like a high-quality commit message to me. 🙌 Let's rebase and merge this into #34, then rebase and merge it to main?

**Review by hanssto — APPROVED** [review]
LGTM, and so green.

**Pull request merged**
